### ISSUE TITLE
fresh installed app not in menu

### ISSUE THREAD

**Issue by lucasemmoreira** [toketas/rn-launcher#7]
Not sure if it is a bug but it is probably an undesired behaviour.

*To reproduce*
I installed zello which was a new app in my phone and the laucher did not have it on the menu

*Solution*
I bet there is some sort of signal when a new app is installed because the default launcher puts on the screen a fresh installed app. However, if this is a "bloated" approach for some reason, you could add a button on the cog menu like `Refresh apps`, or something like that.

**Comment by toketas** [comment]
I was hoping to solve this before someone reports it :smile:
